plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings

remote_theme: pages-themes/tactile@v0.2.0
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
